import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import NavBar from "./components/navbar";
import Header from "./components/header";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <html
        lang="en"
        className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-mono", jetbrainsMono.variable)}
        >
        <body className="min-h-full flex flex-col">
            <div className="flex flex-col">
                <Header/>
                <div>
                    <div className="flex items-center justify-center mt-4 mb-4">
                        <NavBar/>
                    </div>
                    <div className="m-4 ml-90 mr-90"> 
                        {/* fix the spacing because currently it is fixed */}
                        {children}
                    </div>
                </div>
            </div>
        </body>
        </html>
    </>
  );
}
